title: Mwitt Predictor
description: By kiyi#4755 on discord, or (#238) on mweor. A work in progress! This program uses genetic information purely from the community, and as such may not always be 100% accurate. 
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
